export const optionQuantityArmada = [
  { label: '1 L', value: '1 L' },
  { label: '2 L', value: '2 L' },
  { label: '3 L', value: '3 L' },
  { label: '4 L', value: '4 L' },
  { label: '5 L', value: '5 L' },
  { label: '6 L', value: '6 L' },
  { label: '7 L', value: '7 L' },
  { label: '8 L', value: '8 L' },
  { label: '9 L', value: '9 L' },
  { label: '10 L', value: '10 L' },
  { label: '11 L', value: '11 L' },
  { label: '12 L', value: '12 L' },
  { label: '13 L', value: '13 L' },
  { label: '14 L', value: '14 L' },
  { label: '15 L', value: '15 L' },
  { label: '16 L', value: '16 L' },
  { label: 'other', value: 'other' },
]