export const optionQuantityArmada = [
  { label: '1 kL', value: '1 kL' },
  { label: '2 kL', value: '2 kL' },
  { label: '3 kL', value: '3 kL' },
  { label: '4 kL', value: '4 kL' },
  { label: '5 kL', value: '5 kL' },
  { label: '6 kL', value: '6 kL' },
  { label: '7 kL', value: '7 kL' },
  { label: '8 kL', value: '8 kL' },
  { label: '9 kL', value: '9 kL' },
  { label: '10 kL', value: '10 kL' },
  { label: '11 kL', value: '11 kL' },
  { label: '12 kL', value: '12 kL' },
  { label: '13 kL', value: '13 kL' },
  { label: '14 kL', value: '14 kL' },
  { label: '15 kL', value: '15 kL' },
  { label: '16 kL', value: '16 kL' },
  { label: 'other', value: 'other' },
]