name: Release FE

on:
  push:
    branches:
      - feat/workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy env variables
        run: |
          echo "VITE_BASE_URL=https://backstage.primasynergy.com/" >> .env
          echo "VITE_ALGORITHM=aes-256-cbc" >> .env
          echo "VITE_CRYPTO_SECRET_KEY=6d4c6d75567a676f6a724c576b5355714c586d74487347334d684d324f314b6a" >> .env
          echo "VITE_CRYPTO_IV_KEY=3a3b1d1a39567871344951204a426150" >> .env

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run generate
        run: npm run generate

      - name: Push dist folder to release branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin release || git branch release
          git switch release || git checkout -b release
          rm -rf *
          cp -r dist/* .
          git add .
          git commit -m "Update release build from $GITHUB_SHA" || echo "No changes to commit"
          git push origin HEAD:release --force
